export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER";
export const FILTER_TASKS = "FILTER_TASKS";
export const SHOW_ADD_NEW_TEAM_MEMBER = "SHOW_ADD_NEW_TEAM_MEMBER";
export const SHOW_ADD_NEW_TASK = "SHOW_ADD_NEW_TASK";
export const SELECT_TASK = "SELECT_TASK";
